version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# 告诉 RTD 这是一个 Sphinx 项目
sphinx:
  configuration: docs/source/conf.py

# 安装依赖
python:
  install:
    - requirements: docs/requirements.txt
